# Generated by Django 3.2.6 on 2021-09-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_articlemodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='article_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.articlemodel'),
            preserve_default=False,
        ),
    ]
