# Generated by Django 3.2.6 on 2021-09-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_commentmodel_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
