# Generated by Django 3.2.6 on 2021-09-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210907_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='tag',
        ),
        migrations.CreateModel(
            name='ArticleTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.articlemodel')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tagmodel')),
            ],
        ),
    ]
