# Generated by Django 3.2.6 on 2021-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210907_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletagsmodel',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='articletagsmodel',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
