# Generated by Django 3.2.6 on 2021-09-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210906_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tagmodel'),
        ),
    ]
